#config_version=6
##! mode: attract

show_player:
  mode_attract_started:
    attract_display_loop:
      speed: 1
    attract_light_show_spinner:
      speed: 10
    attract_light_show_top:
      speed: 10