#config_version=6
##! mode: base

mode:
  start_events: ball_starting
  priority: 100

variable_player:
  # Slingshots
  s_slingshot_right_active:
    score: 50
  s_slingshot_left_active:
    score: 50

shots:
  left_inlane:
    switch: s_inlane_left
    show_tokens:
      light: l_playfield_left_inlane
  right_inlane:
    switch: s_inlane_right
    show_tokens:
      light: l_playfield_right_inlane

slide_player:
  mode_base_started:
    widgets:
      widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50