#config_version=6
##! mode: base

mode:
  start_events: ball_starting
  priority: 100
  restart_on_next_ball: true

event_player:
  multiplayer_game: player_1_multiplayer_slide
  player_1_ball_started: player_1_multiplayer_slide

# Ball save config for the first 10 seconds of the game
ball_saves:
  default:
    active_time: 10s
    grace_period: 2s
    hurry_up_time: 5s
    enable_events: mode_base_started
    timer_start_events: balldevice_bd_plunger_ball_eject_success
    disable_events: ball_will_end
    auto_launch: true
    balls_to_save: 1
    early_ball_save_events: s_outlane_left_active, s_outlane_right_active

# Scoring for hitting various shots
variable_player:
  # Slingshots
  s_slingshot_right_active:
    score: 50
  s_slingshot_left_active:
    score: 50
  s_upper_slingshot_right_active:
    score: 50
  # Kickouts
  s_middle_kickout_active:
    score: 100
  s_upper_kickout_active:
    score: 100
  # Targets
  s_target_middle_active:
    score: 200
  s_target_right_active:
    score: 200
  s_target_top_active:
    score: 200
  # Drop targets
  s_drop_target_top1_active:
    score: 50
  s_drop_target_top2_active:
    score: 50
  s_drop_target_top3_active:
    score: 50
  s_drop_target_top4_active:
    score: 50
  s_drop_target_top5_active:
    score: 50
  s_drop_target_left1_active:
    score: 50
  s_drop_target_left2_active:
    score: 50
  s_drop_target_left3_active:
    score: 50
  s_drop_target_right1_active:
    score: 50
  s_drop_target_right2_active:
    score: 50
  s_drop_target_right3_active:
    score: 50
  # Bumpers
  s_bumper_top_active:
    score: 50
  s_bumper_middle_active:
    score: 50
  s_bumper_right_active:
    score: 50
  # Orbits
  s_orbit1_active:
    score: 125
  s_orbit2_active:
    score: 125
  # Inlanes
  s_inlane_left_active:
    score: 100
  s_inlane_right_active:
    score: 100
  # Completed combos
  mini_game_complete:
    score: 5000
  drop_target_bank_b_bank_right_down:
    score: 500
  drop_target_bank_b_bank_left_down:
    score: 500

# Shots that can be made on the playfield
shots:
  # Inlanes
  left_inlane:
    switch: s_inlane_left
    show_tokens:
      light: l_playfield_left_inlane
  right_inlane:
    switch: s_inlane_right
    show_tokens:
      light: l_playfield_right_inlane
  # Targets
  top_target:
    switch: s_target_top
    show_tokens:
      light: l_playfield_upper_left_target
  middle_target:
    switch: s_target_middle
    show_tokens:
      light: l_playfield_middle_loop_target
  right_target:
    switch: s_target_right
    show_tokens:
      light: l_playfield_right_of_arrow2
  bumper_middle:
    switch: s_bumper_middle
    show_tokens:
      light: l_playfield_above_arrow
  
  # Mini playfield
  mini_game_1:
    switch: s_mini_playfield_switch1
    show_tokens:
      light: l_playfield_mini_game1
  mini_game_2:
    switch: s_mini_playfield_switch2
    show_tokens:
      light: l_playfield_mini_game2
  mini_game_3:
    switch: s_mini_playfield_switch3
    show_tokens:
      light: l_playfield_mini_game3
  mini_game_4:
    switch: s_mini_playfield_switch4
    show_tokens:
      light: l_playfield_mini_game4

# Groups of shots that can be made
shot_groups:
  mini_game:
    shots: mini_game_1, mini_game_2, mini_game_3, mini_game_4
    enable_events: ball_started
    disable_events: ball_ending

# Sound effects for various events
sound_player:
  # Shoot sound (voice)
  mode_base_started:
    shoot_the_ball:
      loops: 0
    waves:
      loops: 0

  # Background music
  sw_launch_active:
    waikiki:
      loops: -1

  # Sound (voice) for hitting various shots
  s_target_top_active:
    nice_shot:
      loops: 0
  
  # Sound (voice) when the ball is drained
  ball_ending:
    that_happens:
      loops: 0
    waikiki:
      action: stop
  
  # Sound (voice) when completing a combo
  drop_target_bank_b_bank_right_down:
    got_all:
      loops: 0
  drop_target_bank_b_bank_left_down:
    got_all:
      loops: 0
  mini_game_complete:
    got_all:
      loops: 0

  # Sound (voice) for ball save
  ball_save_default_saving_ball:
    oof_that_was_close:
      loops: 0
  
  mode_base_ended:
    waves:
      action: stop

# Visuals for base mode
slide_player:
  single_player_ball_started: player_1_single_player_slide
  player_1_multiplayer_slide: player_1_multiplayer_slide
  player_2_ball_started: player_2_ball_slide
  player_3_ball_started: player_3_ball_slide
  player_4_ball_started: player_4_ball_slide

slides:
  player_1_single_player_slide:
  - type: text
    text: (player1|score)
    style: text_large
    number_grouping: true
    min_digits: 2
    y: middle+10
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    y: bottom+1

  player_1_multiplayer_slide:
  - type: text
    text: (player1|score)
    style: text_large
    number_grouping: true
    min_digits: 2
    y: middle+10
  - type: text
    text: (player2|score)
    style: text_small
    anchor_y: top
    anchor_x: right
    halign: right
    number_grouping: true
    min_digits: 2
    x: right-50
    y: top-25
  - type: text
    text: (player3|score)
    style: text_small
    anchor_y: bottom
    anchor_x: left
    halign: left
    y: bottom+25
    x: left+50
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: text_small
    anchor_y: bottom
    anchor_x: right
    halign: right
    y: bottom+25
    x: right-50
    number_grouping: true
    min_digits: 2
  - type: text
    text: PLAYER (number)    BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    y: bottom+1

  player_2_ball_slide:
  - type: text
    text: (player1|score)
    style: text_small
    anchor_y: top
    anchor_x: left
    halign: left
    number_grouping: true
    min_digits: 2
    x: left+50
    y: top-25
  - type: text
    text: (player2|score)
    style: text_large
    number_grouping: true
    min_digits: 2
    y: middle+10
  - type: text
    text: (player3|score)
    style: text_small
    anchor_y: bottom
    anchor_x: left
    halign: left
    y: bottom+25
    x: left+50
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: text_small
    anchor_y: bottom
    anchor_x: right
    halign: right
    y: bottom+25
    x: right-50
    number_grouping: true
    min_digits: 2
  - type: text
    text: PLAYER (number)    BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    y: bottom+1

  player_3_ball_slide:
  - type: text
    text: (player1|score)
    style: text_small
    anchor_y: top
    anchor_x: left
    halign: left
    number_grouping: true
    min_digits: 2
    x: left+50
    y: top-25
  - type: text
    text: (player2|score)
    style: text_small
    anchor_y: top
    anchor_x: right
    halign: right
    number_grouping: true
    min_digits: 2
    x: right-50
    y: top-25
  - type: text
    text: (player3|score)
    style: text_large
    number_grouping: true
    min_digits: 2
    y: middle+10
  - type: text
    text: (player4|score)
    style: text_small
    anchor_y: bottom
    anchor_x: right
    halign: right
    y: bottom+25
    x: right-50
    number_grouping: true
    min_digits: 2
  - type: text
    text: PLAYER (number)    BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    y: bottom+1

  player_4_ball_slide:
  - type: text
    text: (player1|score)
    style: text_small
    anchor_y: top
    anchor_x: left
    halign: left
    number_grouping: true
    min_digits: 2
    x: left+50
    y: top-25
  - type: text
    text: (player2|score)
    style: text_small
    anchor_y: top
    anchor_x: right
    halign: right
    number_grouping: true
    min_digits: 2
    x: right-50
    y: top-25
  - type: text
    text: (player3|score)
    style: text_small
    anchor_y: bottom
    anchor_x: left
    halign: left
    y: bottom+25
    x: left+50
    number_grouping: true
    min_digits: 2
  - type: text
    style: text_large
    text: (player4|score)
    number_grouping: true
    min_digits: 2
    y: middle+10
  - type: text
    text: PLAYER (number)    BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    y: bottom+1

# Light shows for ball save
show_player:
  ball_save_default_timer_start:
    ball_save_show:
      action: play
      speed: 5
  ball_save_default_hurry_up:
    ball_save_show:
      action: play
      speed: 10
  ball_save_default_disabled:
    ball_save_show:
      action: stop