#config_version=6
##! mode: base

mode:
  start_events: ball_starting
  priority: 100

variable_player:
  # Slingshots
  s_slingshot_right_active:
    score: 50
  s_slingshot_left_active:
    score: 50

shots:
  left_inlane:
    switch: s_inlane_left
    show_tokens:
      light: l_playfield_left_inlane
  right_inlane:
    switch: s_inlane_right
    show_tokens:
      light: l_playfield_right_inlane
  top_target:
    switch: s_target_top
    show_tokens:
      light: l_playfield_upper_left_target
  
  # Mini playfield
  mini_game_1:
    switch: s_mini_playfield_switch1
    show_tokens:
      light: l_playfield_mini_game1
  mini_game_2:
    switch: s_mini_playfield_switch2
    show_tokens:
      light: l_playfield_mini_game2
  mini_game_3:
    switch: s_mini_playfield_switch3
    show_tokens:
      light: l_playfield_mini_game3
  mini_game_4:
    switch: s_mini_playfield_switch4
    show_tokens:
      light: l_playfield_mini_game4

shot_groups:
  mini_game:
    shots: mini_game_1, mini_game_2, mini_game_3, mini_game_4
    enable_events: ball_started
    disable_events: ball_ending

sound_player:
  mode_base_started:
    shoot_the_ball:
      loops: 0

  s_launch_active:
    shoot_the_ball:
      action: stop
    base_background_music:
      loops: -1

  s_target_top_active:
    nice_shot:
      loops: 0
  
  ball_ending:
    that_happens:
      loops: 0

slide_player:
  mode_base_started:
    widgets:
      widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50