#config_version=6

config:
  - hardware.yaml
  - keyboard.yaml
  - display.yaml
  - lights.yaml
  - audio.yaml
  - credits.yaml

modes:
  - base
  - orbit
  - multiball
  - drop_target
  #- credits

game:
  balls_per_game: 3
  max_players: 4

machine:
  balls_installed: 3
  min_balls: 1

widget_styles:
  text_default:
    font_size: 40
    font_name: TropikaIsland-ScriptCasual
  text_small:
    font_size: 30
    font_name: TropikaIsland-ScriptCasual
  text_large:
    font_size: 150
    font_name: TropikaIsland-Int
  icons:
    font_size: 200
    font_name: TropikaIsland-Extras