#config_version=6

displays:
  window:
    default: true
    width: 1280
    height: 390

window:
  title: "Tiki Retreat"
  exit_on_escape: true
  borderless: false
  fullscreen: false
  source_display: window
  width: 1280
  height: 390