#config_version=6

displays:
  window:
    width: 1280
    height: 390
    default: true

window:
  width: 1280
  height: 390
  title: Tiki Retreat
  resizable: true
  borderless: false
  fullscreen: false
  exit_on_escape: true
  source_display: window