#config_version=6

displays:
  window:
    default: true

window:
  title: "Tiki Retreat"
  exit_on_escape: true
  borderless: false
  fullscreen: false
  source_display: window
  #width: 1024
  #height: 786