#config_version=6

displays:
  window:
    width: 1920
    height: 1080
    default: true

window:
  width: 1920
  height: 1080
  title: Tiki Retreat
  resizable: true
  borderless: true
  fullscreen: true
  exit_on_escape: false
  source_display: window
  effects:
    - type: color_dmd
      dots_x: 512
      dots_y: 156
      blur: 0
      background_color: 000000ff
      # gain: 1.2