#config_version=6

hardware:
  platform: fast

fast:
  net:
    controller: neuron
    debug: true
    #port: /dev/tty.usbmodem1101
    io_loop:
      "1616":
        model: FP-I/O-1616
        order: 1
      "3208":
        model: FP-I/O-3208
        order: 2
      cab:
        model: FP-I/O-0024
        order: 3
    watchdog: 1s

  exp:
    boards: 
      leds:
        model: FP-EXP-0071
        led_hz: 30
        led_fade_time: 100ms
  
playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

switches:
  s_start:
    number: cab-2
    tags: start
  s_launch:
    number: cab-3
    tags: launch
  # Flippers
  s_left_flipper:
    number: cab-0
    tags: left_flipper
  s_flipper_left_eos:
    number: 3208-24
  s_right_flipper:
    number: cab-4
    tags: right_flipper
  s_flipper_right_eos:
    number: 3208-25
  s_upper_flipper_left_eos:
    number: 3208-8
    tags: upper_flipper
  s_upper_flipper_right_eos:
    number: 3208-9
  # Trough
  s_trough1:
    number: 3208-0
    type: NC
  s_trough2:
    number: 3208-1
    type: NC
  s_trough3:
    number: 3208-2
    type: NC
  s_trough4:
    number: 3208-3
    type: NC
  s_trough5:
    number: 3208-4
    type: NC
  s_trough6:
    number: 3208-5
    type: NC
  s_trough_jam:
    number: 3208-6
    type: NC
  # Plunger
  s_plunger_lane:
    number: 3208-7
  s_plunger_lane_exit:
    number: 1616-6
    type: NO
  # Slingshots
  s_slingshot_left:
    number: 3208-21
  s_slingshot_right:
    number: 3208-26
  s_upper_slingshot_right:
    number: 1616-14
  # Kickouts
  s_middle_kickout:
    number: 1616-15
  s_upper_kickout:
    number: 1616-13
  # Targets
  s_target_middle:
    number: 3208-10
    debounce: quick
    ignore_window_ms: 1000ms
  s_target_right:
    number: 3208-13
    debounce: quick
    ignore_window_ms: 1000ms
  s_target_top:
    number: 1616-5
    debounce: quick
    ignore_window_ms: 1000ms
  # Drop targets
  s_drop_target_top1:
    number: 1616-9
  s_drop_target_top2:
    number: 1616-10
  s_drop_target_top3:
    number: 1616-11
  s_drop_target_top4:
    number: 1616-12
  s_drop_target_top5:
    number: 1616-8
  s_drop_target_left1:
    number: 3208-18
  s_drop_target_left2:
    number: 3208-19
  s_drop_target_left3:
    number: 3208-20
  s_drop_target_right1:
    type: NC
    number: 3208-29
  s_drop_target_right2:
    number: 3208-30
    type: NC
  s_drop_target_right3:
    number: 3208-31
    type: NC
  # Mini playfield
  s_mini_playfield_switch1:
    number: 1616-0
  s_mini_playfield_switch2:
    number: 1616-1
  s_mini_playfield_switch3:
    number: 1616-2
  s_mini_playfield_switch4:
    number: 1616-3
  # Bumpers
  s_bumper_top:
    number: 1616-4
  s_bumper_middle:
    number: 3208-11
  s_bumper_right:
    number: 3208-12
  # Orbit
  s_orbit1:
    number: 3208-16
  s_orbit2:
    number: 3208-17
  # Inlanes
  s_inlane_left:
    number: 3208-23
    tags: playfield_active, inlane
  s_inlane_right:
    number: 3208-27
    tags: playfield_active, inlane
  # Outlanes
  s_outlane_left:
    number: 3208-22
    tags: playfield_active, outlane
  s_outlane_right:
    number: 3208-28
    tags: playfield_active, outlane

coils:
  # Flipper
  c_flipper_left_main:
    number: 3208-0
    default_pulse_ms: 30
  c_flipper_left_hold:
    number: 3208-1
    max_hold_power: 1.0
  c_flipper_right_main:
    number: 3208-2
    default_pulse_ms: 30
  c_flipper_right_hold:
    number: 3208-3
    max_hold_power: 1.0
  c_upper_flipper_left_main:
    number: 1616-0
    default_pulse_ms: 5
  c_upper_flipper_left_hold:
    number: 1616-1
    max_hold_power: 1.0
  c_upper_flipper_right_main:
    number: 1616-2
    default_pulse_ms: 5
  c_upper_flipper_right_hold:
    number: 1616-3
    max_hold_power: 1.0
  # Trough
  c_trough_eject:
    number: 3208-6
    default_pulse_ms: 5
  # Plunger
  c_plunger:
    number: 3208-7
    default_pulse_ms: 15
  # Slingshots
  c_slingshot_left:
    number: 3208-4
    default_pulse_ms: 5
  c_slingshot_right:
    number: 3208-5
    default_pulse_ms: 5
  c_upper_slingshot_right:
    number: 1616-5
    default_pulse_ms: 5
  # Kickouts
  c_middle_kickout:
    number: 1616-7
    default_pulse_ms: 25
  c_upper_kickout:
    number: 1616-6
    default_pulse_ms: 25
  # Drop targets
  c_drop_target_top_down:
    number: 1616-8
    default_pulse_ms: 20
  c_drop_target_top1:
    number: 1616-13
    default_pulse_ms: 10
  c_drop_target_top2:
    number: 1616-12
    default_pulse_ms: 10
  c_drop_target_top3:
    number: 1616-11
    default_pulse_ms: 10
  c_drop_target_top4:
    number: 1616-10
    default_pulse_ms: 10
  c_drop_target_top5:
    number: 1616-9
    default_pulse_ms: 10
  c_drop_target_left_reset:
    number: 1616-14
    default_pulse_ms: 20
  c_drop_target_right_reset:
    number: 1616-15
    default_pulse_ms: 15
  # Mini playfield
  c_mini_playfield_plunger:
    number: 1616-4
    default_pulse_ms: 2

drop_targets:
  d_top_1:
    switch: s_drop_target_top1
    knockdown_coil: c_drop_target_top1
    knockdown_events: cmd_drop_target_top_1_knockdown
  d_top_2:
    switch: s_drop_target_top2
    knockdown_coil: c_drop_target_top2
    knockdown_events: cmd_drop_target_top_2_knockdown
  d_top_3:
    switch: s_drop_target_top3
    knockdown_coil: c_drop_target_top3
    knockdown_events: cmd_drop_target_top_3_knockdown
  d_top_4:
    switch: s_drop_target_top4
    knockdown_coil: c_drop_target_top4
    knockdown_events: cmd_drop_target_top_4_knockdown
  d_top_5:
    switch: s_drop_target_top5
    knockdown_coil: c_drop_target_top5
    knockdown_events: cmd_drop_target_top_5_knockdown
  d_left_1:
    switch: s_drop_target_left1
    reset_coil: c_drop_target_left_reset
  d_left_2:
    switch: s_drop_target_left2
    reset_coil: c_drop_target_left_reset
  d_left_3:
    switch: s_drop_target_left3
    reset_coil: c_drop_target_left_reset
  d_right_1:
    switch: s_drop_target_right1
    reset_coil: c_drop_target_right_reset
  d_right_2:
    switch: s_drop_target_right2
    reset_coil: c_drop_target_right_reset
  d_right_3:
    switch: s_drop_target_right3
    reset_coil: c_drop_target_right_reset

sequence_shots:
  orbit:
    switch_sequence: s_orbit1, s_orbit2
    sequence_timeout: 3s

drop_target_banks:
  b_bank_top:
    drop_targets: d_top_1, d_top_2, d_top_3, d_top_4, d_top_5
    reset_coils: c_drop_target_top_down
    reset_events: machine_reset_phase_3, ball_starting, cmd_drop_target_bank_top_reset
  b_bank_left:
    drop_targets: d_left_1, d_left_2, d_left_3
    reset_coils: c_drop_target_left_reset
    reset_on_complete: 1s
  b_bank_right:
    drop_targets: d_right_1, d_right_2, d_right_3
    reset_coils: c_drop_target_right_reset
    reset_on_complete: 1s

flippers:
  f_left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    eos_switch: s_flipper_left_eos
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    enable_events: machine_reset_phase_3
  f_right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_flipper_right_eos
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    enable_events: machine_reset_phase_3
  f_upper_flipper_left:
    main_coil: c_upper_flipper_left_main
    hold_coil: c_upper_flipper_left_hold
    activation_switch:  s_left_flipper
    eos_switch: s_upper_flipper_left_eos
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    enable_events: machine_reset_phase_3
  f_upper_flipper_right:
    main_coil: c_upper_flipper_right_main
    hold_coil: c_upper_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_upper_flipper_right_eos
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
    enable_events: machine_reset_phase_3

ball_devices:
  # Trough
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
    debug: true
  # Plunger
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger
    player_controlled_eject_event: sw_launch_active
    confirm_eject_type: switch
    confirm_eject_switch: s_plunger_lane_exit
    eject_timeouts: 3s
  # Scoops
  bd_middle_kickout:
    eject_coil: c_middle_kickout
    ball_switches: s_middle_kickout
    eject_timeouts: 1s
  bd_upper_kickout:
    eject_coil: c_upper_kickout
    ball_switches: s_upper_kickout
    eject_timeouts: 1s

autofire_coils:
  # Slingshots
  af_slingslot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  af_slingslot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  af_upper_slingslot_right:
    coil: c_upper_slingshot_right
    switch: s_upper_slingshot_right
  # Mini playfield
  af_mini_playfield_plunger:
    coil: c_mini_playfield_plunger
    switch: s_target_top

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3