#config_version=6

keyboard:
  "q":
    switch: s_left_flipper
  "w":
    switch: s_right_flipper
  "1":
    switch: s_trough1
    toggle: true
  "2":
    switch: s_trough2
    toggle: true
  "3":
    switch: s_trough3
    toggle: true
  "s":
    switch: s_start
  "a":
    switch: s_launch
  "[":
    switch: s_plunger_lane
  "]":
    switch: s_plunger_lane_exit
  "z":
    event: test_event1
  "x":
    event: test_event2