#config_version=6
  # NOTE: The numbering starts from 1 in the code and 0 on the drawing

#light_settings:
#  default_fade_ms: 250

lights:
  # Lower playfield
  # LED string 1
  # Large arrow shape in the middle of the bottom half of the playfield
  # Arrow middle line from bottom to top
  l_playfield_arrow_middle1:
    number: neuron-1-1 
  l_playfield_arrow_middle2:
    number: neuron-1-2
  l_playfield_arrow_middle3:
    number: neuron-1-3
  l_playfield_arrow_middle4:
    number: neuron-1-4
  l_playfield_arrow_middle5:
    number: neuron-1-5
  l_playfield_arrow_middle6:
    number: neuron-1-6
  l_playfield_arrow_middle7:
    number: neuron-1-7
  l_playfield_arrow_middle8:
    number: neuron-1-8
  l_playfield_arrow_middle9:
    number: neuron-1-9
  l_playfield_arrow_middle10:
    number: neuron-1-10
  # Arrow left arm from bottom to top
  l_playfield_arrow_left1:
    number: neuron-1-15
  l_playfield_arrow_left2:
    number: neuron-1-14
  l_playfield_arrow_left3:
    number: neuron-1-13
  l_playfield_arrow_left4:
    number: neuron-1-12
  l_playfield_arrow_left5:
    number: neuron-1-11
  # Arrow right arm from bottom to top
  l_playfield_arrow_right1:
    number: neuron-1-20
  l_playfield_arrow_right2:
    number: neuron-1-19
  l_playfield_arrow_right3:
    number: neuron-1-18
  l_playfield_arrow_right4:
    number: neuron-1-17
  l_playfield_arrow_right5:
    number: neuron-1-16

  # Three lights to the right of the large arrow shape, starting from the center
  l_playfield_right_of_arrow1:
    number: neuron-1-21
  l_playfield_right_of_arrow2:
    number: neuron-1-22
  l_playfield_right_of_arrow3:
    number: neuron-1-25
  # Left of the large arrow shape
  l_playfield_left_of_arrow:
    number: neuron-1-26
  # Above the large arrow shape
  l_playfield_above_arrow:
    number: neuron-1-27

  # Pointer towards right ramp
  l_playfield_right_ramp1:
    number: neuron-1-23
  l_playfield_right_ramp2:
    number: neuron-1-24
  
  # Pointers middle loop 
  l_playfield_middle_loop_low1:
    number: neuron-1-28
  l_playfield_middle_loop_low2:
    number: neuron-1-29
  l_playfield_middle_loop_up1:
    number: neuron-1-30
  l_playfield_middle_loop_up2:
    number: neuron-1-31

  # LED string 2
  # Middle loop target
  l_playfield_middle_loop_target:
    number: neuron-2-1
  # Left drop target
  l_playfield_left_drop_target:
    number: neuron-2-2

  # Lanes
  # Left outlane
  l_playfield_left_outlane:
    number: neuron-2-3
  # Left inlane
  l_playfield_left_inlane:
    number: neuron-2-4
  # Right outlane
  l_playfield_right_outlane:
    number: neuron-2-12
  # Right inlane
  l_playfield_right_inlane:
    number: neuron-2-11
  
  # Lower four lights
  l_playfield_lower1:
    number: neuron-2-5
  l_playfield_lower2:
    number: neuron-2-8
  l_playfield_lower3:
    number: neuron-2-9
  l_playfield_lower4:
    number: neuron-2-10
  
  # Ball drain
  l_playfield_ball_drain1:
    number: neuron-2-6
  l_playfield_ball_drain2:
    number: neuron-2-7

  # Upper playfield
  # LED string 3
  # Mini game lights
  l_playfield_mini_game1:
    number: neuron-3-1
  l_playfield_mini_game2:
    number: neuron-3-2
  l_playfield_mini_game3:
    number: neuron-3-3
  l_playfield_mini_game4:
    number: neuron-3-4
  
  # Upper playfield left target
  l_playfield_upper_left_target:
    number: neuron-3-5

  # Upper drop target lights
  l_playfield_upper_drop_target1:
    number: neuron-3-6
  l_playfield_upper_drop_target2:
    number: neuron-3-7