#config_version=6
##! mode: drop_target

mode:
  start_events: sw_launch_active
  stop_events: ball_will_end
  priority: 500

# State machine to manage game progression
state_machines:
  drop_sequence:
    states:
      start:
        label: Initial state
        events_when_started: 
          - cmd_knock_down_drop_target_bank
      stage_1:
        label: Target 3 up
        events_when_started: 
          - cmd_reset_drop_target_3|500ms
      stage_2:
        label: Targets 2 and 4 up
        events_when_started: 
          - cmd_reset_drop_targets_2_4|500ms
      stage_3:
        label: Targets 1, 3, and 5 up
        events_when_started:
          - cmd_reset_drop_targets_1_3_5|500ms
      stage_4:
        label: Targets 1, 2, 4, and 5 up
        events_when_started:
          - cmd_reset_drop_targets_1_2_4_5|500ms
      complete:
        label: All targets up
        events_when_started:
          - cmd_drop_target_top_reset
          - cmd_drop_sequence_completed
    transitions:
      - source: start
        target: stage_1
        events: prepare_stage_1
      - source: stage_1
        target: stage_2
        events: drop_target_d_top_3_down
      - source: stage_2
        target: stage_3
        events: drop_target_d_top_2_down, drop_target_d_top_4_down
      - source: stage_3
        target: stage_4
        events: drop_target_d_top_1_down, drop_target_d_top_3_down, drop_target_d_top_5_down
      - source: stage_4
        target: complete
        events: drop_target_d_top_1_down, drop_target_d_top_2_down, drop_target_d_top_4_down, drop_target_d_top_5_down
      - source: complete
        target: start
        events: drop_target_bank_b_bank_top_up

# Event player to handle drop target control
event_player:
  mode_drop_target_started: 
    - cmd_knock_down_drop_target_bank
    - prepare_stage_1|1s
  cmd_knock_down_drop_target_bank: cmd_drop_target_top_down
  cmd_reset_drop_target_3: d_top_1_reset
  cmd_reset_drop_targets_2_4:
    - drop_target_d_top_2_reset
    - drop_target_d_top_4_reset
  cmd_reset_drop_targets_1_3_5:
    - drop_target_d_top_1_reset
    - drop_target_d_top_3_reset
    - drop_target_d_top_5_reset
  cmd_reset_drop_targets_1_2_4_5:
    - drop_target_d_top_1_reset
    - drop_target_d_top_2_reset
    - drop_target_d_top_4_reset
    - drop_target_d_top_5_reset

# Scoring
variable_player:
  d_top_3_down{state_machines.drop_sequence.state=="stage_1"}:
    score: 1000
  d_top_2_down{state_machines.drop_sequence.state=="stage_2"}:
    score: 2000
  d_top_4_down{state_machines.drop_sequence.state=="stage_2"}:
    score: 2000
  d_top_1_down{state_machines.drop_sequence.state=="stage_3"}:
    score: 3000
  d_top_3_down{state_machines.drop_sequence.state=="stage_3"}:
    score: 3000
  d_top_5_down{state_machines.drop_sequence.state=="stage_3"}:
    score: 3000
  d_top_1_down{state_machines.drop_sequence.state=="stage_4"}:
    score: 4000
  d_top_2_down{state_machines.drop_sequence.state=="stage_4"}:
    score: 4000
  d_top_4_down{state_machines.drop_sequence.state=="stage_4"}:
    score: 4000
  d_top_5_down{state_machines.drop_sequence.state=="stage_4"}:
    score: 4000
  cmd_drop_sequence_completed:
    score: 10000