#config_version=5

hardware:
  platform: fast

fast:
  net:
    controller: neuron
    port: /dev/tty.usbmodem142101, /dev/tty.usbmodem144101
    debug: true
    io_loop:
      1616:
        model: FP-I/O-1616
        order: 1
      3208:
        model: FP-I/O-3208
        order: 2

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough

switches:
  # 1616 board
  # Start
  s_start:
    number: 1616-0
    tags: start
  # Launch
  s_launch:
    number: 1616-1
    tags: launch
  # Outhole switch
  s_drain:
    number: 1616-2
  # Trough
  # Also known as runout switch
  s_trough_1:
    number: 1616-3
  s_trough_2:
    number: 1616-4
  s_trough_3:
    number: 1616-5
  # Flippers
  s_flipper_left:
    number: 1616-6
    tags: left_flipper
  s_flipper_left_eos:
    number: 1616-8
  s_flipper_right:
    number: 1616-7
    tags: right_flipper
  s_flipper_right_eos:
    number: 1616-9
  # Slingshots
  s_slingshot_left:
    number: 1616-10
  s_slingshot_right:
    number: 1616-11
  # 3208 board
  # Pop bumpers
  s_pop_bumper_1:
    number: 3208-3
  s_pop_bumper_2:
    number: 3208-4
  s_pop_bumper_3:
    number: 3208-5
  s_pop_bumper_4:
    number: 3208-6
  s_pop_bumper_5:
    number: 3208-7
  # Drop target bank left
  s_drop_target_bank_left_1:
    number: 3208-0
  s_drop_target_bank_left_2:
    number: 3208-1
  s_drop_target_bank_left_3:
    number: 3208-2
  # Drop target bank right
  s_drop_target_bank_right_1:
    number: 3208-8
  s_drop_target_bank_right_2:
    number: 3208-9
  s_drop_target_bank_right_3:
    number: 3208-10
  s_drop_target_bank_right_4:
    number: 3208-11
  s_drop_target_bank_right_5:
    number: 3208-12
  # Top kickout hole
  s_kickout_hole_top:
    number: 3208-13

coils:
  # 1616 board
  # Flipper
  c_flipper_left_main:
    number: 1616-0
    default_pulse_ms: 5
  c_flipper_left_hold:
    number: 1616-1
    default_hold_power: .5
  c_flipper_right_main:
    number: 1616-2
    default_pulse_ms: 5
  c_flipper_right_hold:
    number: 1616-3
    default_hold_power: .5
  # Slingshots
  c_slingshot_left:
    number: 1616-4
    default_pulse_ms: 10
  c_slingshot_right:
    number: 1616-5
    default_pulse_ms: 10
  # Trough
  # Also known as runout coil / outhole coil
  c_drain_eject:
    number: 1616-6
    default_pulse_ms: 40
  # Also known as launch / loader
  c_trough_eject:
    number: 1616-7
    default_pulse_ms: 15
  # Launch
  c_launch:
    number: 1616-8
    default_pulse_ms: 15
  # Kickout hole
  c_kickout_hole_top:
    number: 1616-9
    default_pulse_ms: 10
  # 3208 board
  # Pop bumpers
  c_pop_bumper_1:
    number: 3208-3
    default_pulse_ms: 5
  c_pop_bumper_2:
    number: 3208-4
    default_pulse_ms: 5
  c_pop_bumper_3:
    number: 3208-5
    default_pulse_ms: 5
  c_pop_bumper_4:
    number: 3208-6
    default_pulse_ms: 5
  c_pop_bumper_5:
    number: 3208-7
    default_pulse_ms: 5
  # Drop target bank left
  c_drop_target_bank_left_reset:
    number: 3208-0
    default_pulse_ms: 30
  # Drop target bank right
  c_drop_target_bank_right_2_reset:
    number: 3208-1
    default_pulse_ms: 25
  c_drop_target_bank_right_3_reset:
    number: 3208-2
    default_pulse_ms: 30

autofire_coils:
  # Trough
  # Automatically load balls into the trough
  # af_trough_loader:
  #  coil: c_drain_eject
  #  switch: s_drain
  # Slingshots
  af_slingslot_left:
    coil: c_slingshot_left
    switch: s_slingshot_left
  af_slingslot_right:
    coil: c_slingshot_right
    switch: s_slingshot_right
  # Launch ball when launch switch is pressed
  af_launch:
    coil: c_launch
    switch: s_launch
  # Kickout hole
  af_kickout_hole_top:
    coil: c_kickout_hole_top
    switch: s_kickout_hole_top
  # Pop bumpers
  af_pop_bumper_1:
    coil: c_pop_bumper_1
    switch: s_pop_bumper_1
  af_pop_bumper_2:
    coil: c_pop_bumper_2
    switch: s_pop_bumper_2
  af_pop_bumper_3:
    coil: c_pop_bumper_3
    switch: s_pop_bumper_3
  af_pop_bumper_4:
    coil: c_pop_bumper_4
    switch: s_pop_bumper_4
  af_pop_bumper_5:
    coil: c_pop_bumper_5
    switch: s_pop_bumper_5

drop_targets:
  drop_target_left_1:
    switch: s_drop_target_bank_left_1
  drop_target_left_2:
    switch: s_drop_target_bank_left_2
  drop_target_left_3:
    switch: s_drop_target_bank_left_3
  drop_target_right_1:
    switch: s_drop_target_bank_right_1
  drop_target_right_2:
    switch: s_drop_target_bank_right_2
  drop_target_right_3:
    switch: s_drop_target_bank_right_3
  drop_target_right_4:
    switch: s_drop_target_bank_right_4
  drop_target_right_5:
    switch: s_drop_target_bank_right_5
drop_target_banks:
  left_bank:
    drop_targets: drop_target_left_1, drop_target_left_2, drop_target_left_3
    reset_coils: c_drop_target_bank_left_reset
    reset_on_complete: 1s
  right_bank:
    drop_targets: drop_target_right_1, drop_target_right_2, drop_target_right_3, drop_target_right_4, drop_target_right_5
    reset_coils: c_drop_target_bank_right_2_reset, c_drop_target_bank_right_3_reset
    reset_on_complete: 1s

ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain_eject
    eject_targets: bd_trough
    eject_timeouts: 3s
    tags: drain
  bd_trough:
    eject_coil: c_trough_eject
    ball_switches: s_trough_1, s_trough_2, s_trough_3
    tags: home, trough
    eject_timeouts: 3s
    debug: true

flippers:
  f_flipper_left:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_flipper_left
    eos_switch: s_flipper_left_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500
  f_flipper_right:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_flipper_right
    eos_switch: s_flipper_right_eos
    use_eos: true
    repulse_on_eos_open: true
    eos_active_ms_before_repulse: 500

virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3